name: strainmap_ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - setuptools
  - toml
  - numpy
  - keras
  - tensorflow-gpu
  - opencv
  - matplotlib
  - xarray
  - dask
  - netcdf4
  - pip:
    - tensorlayer
