#PBS -lselect=1:ncpus=16:mem=96gb:ngpus=4:gpu_type=RTX6000
#PBS -lwalltime=01:00:00

module load anaconda3/personal
module load cuda

source activate strainmap_ai

cd $PBS_O_WORKDIR

# Generic:
# python -m strainmap_ai NETCDF_FILES --model_path TRAINED_MODEL --test PATIENT1,PATIENT2
python -m strainmap_ai $RDS_PROJECT/strainmap/live/Data/ --model_path trained/crop64_int16_all_with_test --test WS,AD

